// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dgallkbqqitadzicyltl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRnYWxsa2JxcWl0YWR6aWN5bHRsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzQ4Mjg4MzIsImV4cCI6MjA5MDQwNDgzMn0.d3I6LCO1WDXM-qCs6SLj6MtnXJCXsRHTYnBcxv8u-QM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});